PLP-5 : Job Table
karan316/Placement-Portal pull request #5
Opened 2021-12-01 10:59 UTC by sarthakagrawal927

2021-12-04 05:28 UTC, karan316 commented
![Screenshot_20211204_104932](https://user-images.githubusercontent.com/39960656/144698305-84c09f98-e5ba-4a36-b5ab-f6732c768a00.png)

- Spacing between top bar and table is not equal
![Screenshot_20211204_104907](https://user-images.githubusercontent.com/39960656/144698341-8622bd43-8b32-4b75-9be8-1c22b19d1615.png)

- The table should have rounded corners
- decrease the logo size a bit
- use ui.darkGray for filter and sort text and icon
- decrease the search icon size in the search bar
- use the SVG from figma for sort

2021-12-04 05:37 UTC, karan316 commented
**FEW MINOR CHANGES IN SIDEBAR**

- use `aside` as the container instead of div
- reduce the width to 15%
- justify center the text inside the tab
- font-weight 500 
- remove text transform uppercase

2021-12-04 06:12 UTC, karan316 requested changes

2021-12-04 06:12 UTC, karan316 commented on client/components/TableRow/index.tsx
> +			key={company.stipend + index}
use company id as key

2021-12-04 06:12 UTC, karan316 commented on client/components/TableRow/statusCell.tsx
> +
you can use a [chip](https://mui.com/components/chips/) component from MUI, but don't change if this works. If possible create a separate component called Badge in the components folder and import it from there because we might use this component in many places. Move the color map over there as well.

2021-12-04 12:57 UTC, sarthakagrawal927 commented on client/components/TableCell/index.tsx
> +		>
Added styles here because they were common to both header & body cell

2021-12-04 12:58 UTC, sarthakagrawal927 commented on client/components/TableRow/index.tsx
> +			key={company.stipend + index}
aah id right, but 1 company can come for multiple profiles ?

2021-12-04 12:59 UTC, sarthakagrawal927 commented on client/components/TableRow/statusCell.tsx
> +
This is something I still need to work on, currently creating colorMap for every row, inefficient

2021-12-04 12:59 UTC, sarthakagrawal927 commented on client/components/SearchBar/index.js
> +		<Paper
IDK, copy pasted from inputBase material UI, works fine

2021-12-04 13:17 UTC, sarthakagrawal927 commented on client/components/TableRow/index.tsx
> +			key={company.stipend + index}
will do when data comes from backend

2021-12-04 13:17 UTC, sarthakagrawal927 commented on client/components/TableRow/companyCell.tsx
> +				<img src={logo} alt={name} style={{ width: "50px", height: "50px" }} />
When in percentage the table cell takes too much space, making the table ugly

2021-12-06 11:40 UTC, sarthakagrawal927 commented on client/components/TableCell/index.tsx
> +};
Ha I did that, deepsource wanted this XD

2021-12-10 06:15 UTC, karan316 approved these changes

2021-12-10 06:15 UTC, merged